name: GitHub-Profile-Summary-Cards

on:
  workflow_dispatch: # permite execução manual
  schedule:
    - cron: "0 0 * * *" # opcional: executa diariamente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Generate Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          THEME: holi

      - name: Generate App Token
        id: generate_token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Commit and Push
        run: |
          git config user.name "NexusHub-Bot[bot]"
          git config user.email "320790022+NexusHub-Bot[bot]@users.noreply.github.com"
          
          git remote set-url origin https://x-access-token:${{ steps.generate_token.outputs.token }}@github.com/${{ github.repository }}.git

          git add profile-summary-card-output/
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update GitHub stats [skip ci]"
          git push
