name: GitHub-Profile-Summary-Cards

on:
  workflow_dispatch:  # permite execução manual
  schedule:
    - cron: "0 0 * * *"  # opcional: executa diariamente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: DoctorSolo/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
